[runner]
fastReruns = true

[client]
# toolbarMode="minimal"
showSidebarNavigation = false

[server]
#enableCORS=false
#enableXsrfProtection=false
enableStaticServing=true

[browser]
gatherUsageStats = false